version: '3'

services:
  app:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/products?autoReconnect=true&useSSL=false
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    build: .docker/mysql
    image: mysql:5.7
    restart: always
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=products
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=123456
    networks:
      - app-network

networks:
  app-network:
    driver: bridge